Default: &defaults
  database: LstCom.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: LstCom_test.sqlite3
  <<: *defaults

Staging:
  database: LstCom_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: LstCom_production.sqlite3
  poolsize: 100
  <<: *defaults
